# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20170524_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
