# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_pizza_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
    ]
