# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='pizza',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
        ),
    ]
