# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0010_bebida_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizzas.Pizza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
