# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0011_auto_20170524_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
