# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_auto_20170524_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
